from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any
from typing import TypeVar
from typing import cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.batch_fields_create_user_type import BatchFieldsCreateUserType
from ..models.batch_fields_data_direction import BatchFieldsDataDirection
from ..models.batch_fields_state import BatchFieldsState
from ..models.batch_fields_states_item import BatchFieldsStatesItem
from ..models.batch_fields_transfer_directions_item import (
    BatchFieldsTransferDirectionsItem,
)
from ..models.batch_fields_type import BatchFieldsType
from ..types import UNSET
from ..types import Unset

T = TypeVar("T", bound="BatchFields")


@_attrs_define
class BatchFields:
    """
    Attributes:
        id (float | Unset): The batch ID Example: 1.
        create_user_id (float | Unset): The user ID of the user who created the batch Example: 1.
        create_user_full_name (str | Unset): The full name of the user who created the batch Example: Max Mustermann.
        create_user_type (BatchFieldsCreateUserType | Unset): The type of the create user Example: client.
        update_user_id (float | Unset): The user ID of the user who updated the batch Example: 1.
        update_user_full_name (None | str | Unset): The full name of the user who updated the batch Example: Max
            Mustermann.
        type_ (BatchFieldsType | Unset): The type of the batch Example: icl.
        test (bool | Unset): Indicates if the batch is a test batch Example: True.
        file_nbr_of_transactions (float | None | Unset): The number of transactions in the batch file (Might be null
            because confidential) Example: 10.
        file_create_date_time (datetime.datetime | Unset): The date and time when the batch file was created (Stored as
            UTC, formatted as zero UTC offset (Zulu) format) Example: 2024-02-04T23:00:00.000Z.
        file_total_amount (float | None | Unset): The total amount of the batch file (push/pull/return NOT respected!)
            (Number of cents) (Might be null because confidential) Example: 1000.
        create_date_time (datetime.datetime | Unset): The date and time when the batch was created (Stored as UTC,
            formatted as zero UTC offset (Zulu) format) Example: 2024-02-04T23:00:00.000Z.
        update_date_time (datetime.datetime | Unset): The date and time when the batch was update (Stored as UTC,
            formatted as zero UTC offset (Zulu) format) Example: 2024-02-04T23:00:00.000Z.
        state (BatchFieldsState | Unset): The state of the batch Example: created.
        external_key (None | str | Unset): External key of the batch Example: ABC123456789.
        contains_virtual_transactions (bool | Unset): Signifies that virtual accounts are expected in all transactions
        uploaded_filename (None | str | Unset): The filename of the uploaded file Example: merged_batch_id_123.ach.
        transfer_directions (list[BatchFieldsTransferDirectionsItem] | Unset):
        states (list[BatchFieldsStatesItem] | Unset):
        company_names (list[str] | Unset):
        transaction_ids (list[float] | Unset):
        nbr_of_transactions (float | Unset): The number of transactions in the batch Example: 10.
        total_amount (float | Unset): The total amount of the batch (push/pull/return NOT respected!) (Number of cents)
            Example: 1000.
        comment_count (float | Unset): The number of comments that exist on the transaction
        contains_return_transactions (bool | Unset): Tells if the batch's transactions contain returns. We assume a
            batch file with returns contains exclusively returns. Returns generated by our API always contains only one.
        data_direction (BatchFieldsDataDirection | Unset): Whether the batch file is outgoing or came in by another
            bank. Fintech API batches are always outgoing. API generated Returns are outgoing. Example: outgoing.
    """

    id: float | Unset = UNSET
    create_user_id: float | Unset = UNSET
    create_user_full_name: str | Unset = UNSET
    create_user_type: BatchFieldsCreateUserType | Unset = UNSET
    update_user_id: float | Unset = UNSET
    update_user_full_name: None | str | Unset = UNSET
    type_: BatchFieldsType | Unset = UNSET
    test: bool | Unset = UNSET
    file_nbr_of_transactions: float | None | Unset = UNSET
    file_create_date_time: datetime.datetime | Unset = UNSET
    file_total_amount: float | None | Unset = UNSET
    create_date_time: datetime.datetime | Unset = UNSET
    update_date_time: datetime.datetime | Unset = UNSET
    state: BatchFieldsState | Unset = UNSET
    external_key: None | str | Unset = UNSET
    contains_virtual_transactions: bool | Unset = UNSET
    uploaded_filename: None | str | Unset = UNSET
    transfer_directions: list[BatchFieldsTransferDirectionsItem] | Unset = UNSET
    states: list[BatchFieldsStatesItem] | Unset = UNSET
    company_names: list[str] | Unset = UNSET
    transaction_ids: list[float] | Unset = UNSET
    nbr_of_transactions: float | Unset = UNSET
    total_amount: float | Unset = UNSET
    comment_count: float | Unset = UNSET
    contains_return_transactions: bool | Unset = UNSET
    data_direction: BatchFieldsDataDirection | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        create_user_id = self.create_user_id

        create_user_full_name = self.create_user_full_name

        create_user_type: str | Unset = UNSET
        if not isinstance(self.create_user_type, Unset):
            create_user_type = self.create_user_type.value

        update_user_id = self.update_user_id

        update_user_full_name: None | str | Unset
        if isinstance(self.update_user_full_name, Unset):
            update_user_full_name = UNSET
        else:
            update_user_full_name = self.update_user_full_name

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        test = self.test

        file_nbr_of_transactions: float | None | Unset
        if isinstance(self.file_nbr_of_transactions, Unset):
            file_nbr_of_transactions = UNSET
        else:
            file_nbr_of_transactions = self.file_nbr_of_transactions

        file_create_date_time: str | Unset = UNSET
        if not isinstance(self.file_create_date_time, Unset):
            file_create_date_time = self.file_create_date_time.isoformat()

        file_total_amount: float | None | Unset
        if isinstance(self.file_total_amount, Unset):
            file_total_amount = UNSET
        else:
            file_total_amount = self.file_total_amount

        create_date_time: str | Unset = UNSET
        if not isinstance(self.create_date_time, Unset):
            create_date_time = self.create_date_time.isoformat()

        update_date_time: str | Unset = UNSET
        if not isinstance(self.update_date_time, Unset):
            update_date_time = self.update_date_time.isoformat()

        state: str | Unset = UNSET
        if not isinstance(self.state, Unset):
            state = self.state.value

        external_key: None | str | Unset
        if isinstance(self.external_key, Unset):
            external_key = UNSET
        else:
            external_key = self.external_key

        contains_virtual_transactions = self.contains_virtual_transactions

        uploaded_filename: None | str | Unset
        if isinstance(self.uploaded_filename, Unset):
            uploaded_filename = UNSET
        else:
            uploaded_filename = self.uploaded_filename

        transfer_directions: list[str] | Unset = UNSET
        if not isinstance(self.transfer_directions, Unset):
            transfer_directions = []
            for transfer_directions_item_data in self.transfer_directions:
                transfer_directions_item = transfer_directions_item_data.value
                transfer_directions.append(transfer_directions_item)

        states: list[str] | Unset = UNSET
        if not isinstance(self.states, Unset):
            states = []
            for states_item_data in self.states:
                states_item = states_item_data.value
                states.append(states_item)

        company_names: list[str] | Unset = UNSET
        if not isinstance(self.company_names, Unset):
            company_names = self.company_names

        transaction_ids: list[float] | Unset = UNSET
        if not isinstance(self.transaction_ids, Unset):
            transaction_ids = self.transaction_ids

        nbr_of_transactions = self.nbr_of_transactions

        total_amount = self.total_amount

        comment_count = self.comment_count

        contains_return_transactions = self.contains_return_transactions

        data_direction: str | Unset = UNSET
        if not isinstance(self.data_direction, Unset):
            data_direction = self.data_direction.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if id is not UNSET:
            field_dict["id"] = id
        if create_user_id is not UNSET:
            field_dict["create_user_id"] = create_user_id
        if create_user_full_name is not UNSET:
            field_dict["create_user_full_name"] = create_user_full_name
        if create_user_type is not UNSET:
            field_dict["create_user_type"] = create_user_type
        if update_user_id is not UNSET:
            field_dict["update_user_id"] = update_user_id
        if update_user_full_name is not UNSET:
            field_dict["update_user_full_name"] = update_user_full_name
        if type_ is not UNSET:
            field_dict["type"] = type_
        if test is not UNSET:
            field_dict["test"] = test
        if file_nbr_of_transactions is not UNSET:
            field_dict["file_nbr_of_transactions"] = file_nbr_of_transactions
        if file_create_date_time is not UNSET:
            field_dict["file_create_date_time"] = file_create_date_time
        if file_total_amount is not UNSET:
            field_dict["file_total_amount"] = file_total_amount
        if create_date_time is not UNSET:
            field_dict["create_date_time"] = create_date_time
        if update_date_time is not UNSET:
            field_dict["update_date_time"] = update_date_time
        if state is not UNSET:
            field_dict["state"] = state
        if external_key is not UNSET:
            field_dict["external_key"] = external_key
        if contains_virtual_transactions is not UNSET:
            field_dict["contains_virtual_transactions"] = contains_virtual_transactions
        if uploaded_filename is not UNSET:
            field_dict["uploaded_filename"] = uploaded_filename
        if transfer_directions is not UNSET:
            field_dict["transfer_directions"] = transfer_directions
        if states is not UNSET:
            field_dict["states"] = states
        if company_names is not UNSET:
            field_dict["company_names."] = company_names
        if transaction_ids is not UNSET:
            field_dict["transaction_ids"] = transaction_ids
        if nbr_of_transactions is not UNSET:
            field_dict["nbr_of_transactions"] = nbr_of_transactions
        if total_amount is not UNSET:
            field_dict["total_amount"] = total_amount
        if comment_count is not UNSET:
            field_dict["comment_count"] = comment_count
        if contains_return_transactions is not UNSET:
            field_dict["contains_return_transactions"] = contains_return_transactions
        if data_direction is not UNSET:
            field_dict["data_direction"] = data_direction

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id", UNSET)

        create_user_id = d.pop("create_user_id", UNSET)

        create_user_full_name = d.pop("create_user_full_name", UNSET)

        _create_user_type = d.pop("create_user_type", UNSET)
        create_user_type: BatchFieldsCreateUserType | Unset
        if isinstance(_create_user_type, Unset):
            create_user_type = UNSET
        else:
            create_user_type = BatchFieldsCreateUserType(_create_user_type)

        update_user_id = d.pop("update_user_id", UNSET)

        def _parse_update_user_full_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        update_user_full_name = _parse_update_user_full_name(
            d.pop("update_user_full_name", UNSET)
        )

        _type_ = d.pop("type", UNSET)
        type_: BatchFieldsType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = BatchFieldsType(_type_)

        test = d.pop("test", UNSET)

        def _parse_file_nbr_of_transactions(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        file_nbr_of_transactions = _parse_file_nbr_of_transactions(
            d.pop("file_nbr_of_transactions", UNSET)
        )

        _file_create_date_time = d.pop("file_create_date_time", UNSET)
        file_create_date_time: datetime.datetime | Unset
        if isinstance(_file_create_date_time, Unset):
            file_create_date_time = UNSET
        else:
            file_create_date_time = isoparse(_file_create_date_time)

        def _parse_file_total_amount(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        file_total_amount = _parse_file_total_amount(d.pop("file_total_amount", UNSET))

        _create_date_time = d.pop("create_date_time", UNSET)
        create_date_time: datetime.datetime | Unset
        if isinstance(_create_date_time, Unset):
            create_date_time = UNSET
        else:
            create_date_time = isoparse(_create_date_time)

        _update_date_time = d.pop("update_date_time", UNSET)
        update_date_time: datetime.datetime | Unset
        if isinstance(_update_date_time, Unset):
            update_date_time = UNSET
        else:
            update_date_time = isoparse(_update_date_time)

        _state = d.pop("state", UNSET)
        state: BatchFieldsState | Unset
        if isinstance(_state, Unset):
            state = UNSET
        else:
            state = BatchFieldsState(_state)

        def _parse_external_key(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        external_key = _parse_external_key(d.pop("external_key", UNSET))

        contains_virtual_transactions = d.pop("contains_virtual_transactions", UNSET)

        def _parse_uploaded_filename(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        uploaded_filename = _parse_uploaded_filename(d.pop("uploaded_filename", UNSET))

        _transfer_directions = d.pop("transfer_directions", UNSET)
        transfer_directions: list[BatchFieldsTransferDirectionsItem] | Unset = UNSET
        if _transfer_directions is not UNSET:
            transfer_directions = []
            for transfer_directions_item_data in _transfer_directions:
                transfer_directions_item = BatchFieldsTransferDirectionsItem(
                    transfer_directions_item_data
                )

                transfer_directions.append(transfer_directions_item)

        _states = d.pop("states", UNSET)
        states: list[BatchFieldsStatesItem] | Unset = UNSET
        if _states is not UNSET:
            states = []
            for states_item_data in _states:
                states_item = BatchFieldsStatesItem(states_item_data)

                states.append(states_item)

        company_names = cast(list[str], d.pop("company_names.", UNSET))

        transaction_ids = cast(list[float], d.pop("transaction_ids", UNSET))

        nbr_of_transactions = d.pop("nbr_of_transactions", UNSET)

        total_amount = d.pop("total_amount", UNSET)

        comment_count = d.pop("comment_count", UNSET)

        contains_return_transactions = d.pop("contains_return_transactions", UNSET)

        _data_direction = d.pop("data_direction", UNSET)
        data_direction: BatchFieldsDataDirection | Unset
        if isinstance(_data_direction, Unset):
            data_direction = UNSET
        else:
            data_direction = BatchFieldsDataDirection(_data_direction)

        batch_fields = cls(
            id=id,
            create_user_id=create_user_id,
            create_user_full_name=create_user_full_name,
            create_user_type=create_user_type,
            update_user_id=update_user_id,
            update_user_full_name=update_user_full_name,
            type_=type_,
            test=test,
            file_nbr_of_transactions=file_nbr_of_transactions,
            file_create_date_time=file_create_date_time,
            file_total_amount=file_total_amount,
            create_date_time=create_date_time,
            update_date_time=update_date_time,
            state=state,
            external_key=external_key,
            contains_virtual_transactions=contains_virtual_transactions,
            uploaded_filename=uploaded_filename,
            transfer_directions=transfer_directions,
            states=states,
            company_names=company_names,
            transaction_ids=transaction_ids,
            nbr_of_transactions=nbr_of_transactions,
            total_amount=total_amount,
            comment_count=comment_count,
            contains_return_transactions=contains_return_transactions,
            data_direction=data_direction,
        )

        batch_fields.additional_properties = d
        return batch_fields

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
