from enum import Enum


class WebhookEventTypes(str, Enum):
    ACH_TRANSACTION_CREATE_FAILED = "ach_transaction_create_failed"
    BOOK_TRANSACTION_CREATE_FAILED = "book_transaction_create_failed"
    ICL_TRANSACTION_CREATE_FAILED = "icl_transaction_create_failed"
    INBOUND_ACH_TRANSACTION_CANCELED = "inbound_ach_transaction_canceled"
    INBOUND_ACH_TRANSACTION_CREATED = "inbound_ach_transaction_created"
    INBOUND_ACH_TRANSACTION_FAILED = "inbound_ach_transaction_failed"
    INBOUND_ACH_TRANSACTION_POSTED = "inbound_ach_transaction_posted"
    INBOUND_ACH_TRANSACTION_PROCESSED = "inbound_ach_transaction_processed"
    INBOUND_ACH_TRANSACTION_PROCESSING = "inbound_ach_transaction_processing"
    INBOUND_ACH_TRANSACTION_UNDER_REVIEW = "inbound_ach_transaction_under_review"
    INBOUND_ACH_TRANSACTION_UPDATED = "inbound_ach_transaction_updated"
    INBOUND_BOOK_TRANSACTION_CANCELED = "inbound_book_transaction_canceled"
    INBOUND_BOOK_TRANSACTION_CREATED = "inbound_book_transaction_created"
    INBOUND_BOOK_TRANSACTION_FAILED = "inbound_book_transaction_failed"
    INBOUND_BOOK_TRANSACTION_POSTED = "inbound_book_transaction_posted"
    INBOUND_BOOK_TRANSACTION_PROCESSED = "inbound_book_transaction_processed"
    INBOUND_BOOK_TRANSACTION_PROCESSING = "inbound_book_transaction_processing"
    INBOUND_BOOK_TRANSACTION_UNDER_REVIEW = "inbound_book_transaction_under_review"
    INBOUND_BOOK_TRANSACTION_UPDATED = "inbound_book_transaction_updated"
    INBOUND_ICL_TRANSACTION_CANCELED = "inbound_icl_transaction_canceled"
    INBOUND_ICL_TRANSACTION_CREATED = "inbound_icl_transaction_created"
    INBOUND_ICL_TRANSACTION_FAILED = "inbound_icl_transaction_failed"
    INBOUND_ICL_TRANSACTION_POSTED = "inbound_icl_transaction_posted"
    INBOUND_ICL_TRANSACTION_PROCESSED = "inbound_icl_transaction_processed"
    INBOUND_ICL_TRANSACTION_PROCESSING = "inbound_icl_transaction_processing"
    INBOUND_ICL_TRANSACTION_UNDER_REVIEW = "inbound_icl_transaction_under_review"
    INBOUND_ICL_TRANSACTION_UPDATED = "inbound_icl_transaction_updated"
    INBOUND_WIRE20022_TRANSACTION_CANCELED = "inbound_wire20022_transaction_canceled"
    INBOUND_WIRE20022_TRANSACTION_CREATED = "inbound_wire20022_transaction_created"
    INBOUND_WIRE20022_TRANSACTION_FAILED = "inbound_wire20022_transaction_failed"
    INBOUND_WIRE20022_TRANSACTION_POSTED = "inbound_wire20022_transaction_posted"
    INBOUND_WIRE20022_TRANSACTION_PROCESSED = "inbound_wire20022_transaction_processed"
    INBOUND_WIRE20022_TRANSACTION_PROCESSING = (
        "inbound_wire20022_transaction_processing"
    )
    INBOUND_WIRE20022_TRANSACTION_UNDER_REVIEW = (
        "inbound_wire20022_transaction_under_review"
    )
    INBOUND_WIRE20022_TRANSACTION_UPDATED = "inbound_wire20022_transaction_updated"
    INBOUND_WIRE_TRANSACTION_CANCELED = "inbound_wire_transaction_canceled"
    INBOUND_WIRE_TRANSACTION_CREATED = "inbound_wire_transaction_created"
    INBOUND_WIRE_TRANSACTION_FAILED = "inbound_wire_transaction_failed"
    INBOUND_WIRE_TRANSACTION_POSTED = "inbound_wire_transaction_posted"
    INBOUND_WIRE_TRANSACTION_PROCESSED = "inbound_wire_transaction_processed"
    INBOUND_WIRE_TRANSACTION_PROCESSING = "inbound_wire_transaction_processing"
    INBOUND_WIRE_TRANSACTION_UNDER_REVIEW = "inbound_wire_transaction_under_review"
    INBOUND_WIRE_TRANSACTION_UPDATED = "inbound_wire_transaction_updated"
    OUTBOUND_ACH_TRANSACTION_CANCELED = "outbound_ach_transaction_canceled"
    OUTBOUND_ACH_TRANSACTION_CREATED = "outbound_ach_transaction_created"
    OUTBOUND_ACH_TRANSACTION_FAILED = "outbound_ach_transaction_failed"
    OUTBOUND_ACH_TRANSACTION_POSTED = "outbound_ach_transaction_posted"
    OUTBOUND_ACH_TRANSACTION_PROCESSED = "outbound_ach_transaction_processed"
    OUTBOUND_ACH_TRANSACTION_PROCESSING = "outbound_ach_transaction_processing"
    OUTBOUND_ACH_TRANSACTION_UNDER_REVIEW = "outbound_ach_transaction_under_review"
    OUTBOUND_ACH_TRANSACTION_UPDATED = "outbound_ach_transaction_updated"
    OUTBOUND_BOOK_TRANSACTION_CANCELED = "outbound_book_transaction_canceled"
    OUTBOUND_BOOK_TRANSACTION_CREATED = "outbound_book_transaction_created"
    OUTBOUND_BOOK_TRANSACTION_FAILED = "outbound_book_transaction_failed"
    OUTBOUND_BOOK_TRANSACTION_POSTED = "outbound_book_transaction_posted"
    OUTBOUND_BOOK_TRANSACTION_PROCESSED = "outbound_book_transaction_processed"
    OUTBOUND_BOOK_TRANSACTION_PROCESSING = "outbound_book_transaction_processing"
    OUTBOUND_BOOK_TRANSACTION_UNDER_REVIEW = "outbound_book_transaction_under_review"
    OUTBOUND_BOOK_TRANSACTION_UPDATED = "outbound_book_transaction_updated"
    OUTBOUND_ICL_TRANSACTION_CANCELED = "outbound_icl_transaction_canceled"
    OUTBOUND_ICL_TRANSACTION_CREATED = "outbound_icl_transaction_created"
    OUTBOUND_ICL_TRANSACTION_FAILED = "outbound_icl_transaction_failed"
    OUTBOUND_ICL_TRANSACTION_POSTED = "outbound_icl_transaction_posted"
    OUTBOUND_ICL_TRANSACTION_PROCESSED = "outbound_icl_transaction_processed"
    OUTBOUND_ICL_TRANSACTION_PROCESSING = "outbound_icl_transaction_processing"
    OUTBOUND_ICL_TRANSACTION_UNDER_REVIEW = "outbound_icl_transaction_under_review"
    OUTBOUND_ICL_TRANSACTION_UPDATED = "outbound_icl_transaction_updated"
    OUTBOUND_WIRE20022_TRANSACTION_CANCELED = "outbound_wire20022_transaction_canceled"
    OUTBOUND_WIRE20022_TRANSACTION_CREATED = "outbound_wire20022_transaction_created"
    OUTBOUND_WIRE20022_TRANSACTION_FAILED = "outbound_wire20022_transaction_failed"
    OUTBOUND_WIRE20022_TRANSACTION_POSTED = "outbound_wire20022_transaction_posted"
    OUTBOUND_WIRE20022_TRANSACTION_PROCESSED = (
        "outbound_wire20022_transaction_processed"
    )
    OUTBOUND_WIRE20022_TRANSACTION_PROCESSING = (
        "outbound_wire20022_transaction_processing"
    )
    OUTBOUND_WIRE20022_TRANSACTION_UNDER_REVIEW = (
        "outbound_wire20022_transaction_under_review"
    )
    OUTBOUND_WIRE20022_TRANSACTION_UPDATED = "outbound_wire20022_transaction_updated"
    OUTBOUND_WIRE_TRANSACTION_CANCELED = "outbound_wire_transaction_canceled"
    OUTBOUND_WIRE_TRANSACTION_CREATED = "outbound_wire_transaction_created"
    OUTBOUND_WIRE_TRANSACTION_FAILED = "outbound_wire_transaction_failed"
    OUTBOUND_WIRE_TRANSACTION_POSTED = "outbound_wire_transaction_posted"
    OUTBOUND_WIRE_TRANSACTION_PROCESSED = "outbound_wire_transaction_processed"
    OUTBOUND_WIRE_TRANSACTION_PROCESSING = "outbound_wire_transaction_processing"
    OUTBOUND_WIRE_TRANSACTION_UNDER_REVIEW = "outbound_wire_transaction_under_review"
    OUTBOUND_WIRE_TRANSACTION_UPDATED = "outbound_wire_transaction_updated"
    SUBCLIENT_APPROVED = "subclient_approved"
    SUBCLIENT_CREATED = "subclient_created"
    SUBCLIENT_PENDING = "subclient_pending"
    SUBCLIENT_REJECTED = "subclient_rejected"
    SUBCLIENT_UPDATED = "subclient_updated"
    WIRE20022_TRANSACTION_CREATE_FAILED = "wire20022_transaction_create_failed"
    WIRE_TRANSACTION_CREATE_FAILED = "wire_transaction_create_failed"

    def __str__(self) -> str:
        return str(self.value)
